config/routes.rb
Rails.application.routes.draw do
  resources :pages

  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, presence: true
  has_one_attached :screenshot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :screenshot)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  # This could be nicer if we use the draper gem
  def screenshot_for(page)
    return nil unless page.screenshot.attachment

    image_tag(page.screenshot.variant(resize: '350').processed, width: '100%')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :screenshot %>
    <%= form.file_field :screenshot %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Destroy', page_path(@page), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>
<p><%= t('.description') %></p>

<div class="pages">
  <% @pages.each do |page| %>
    <%= link_to page, class: 'page' do %>
      <div class="page-title">
        <%= page.title %>
      </div>
      <div class="page-screenshot">
        <%= screenshot_for page %>
      </div>
    <% end %>
  <% end %>
</div>

<br>

<%= link_to t('.new_page'), new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Page: <%= @page.title %>
</h1>

<div class="page">
  <div class="page-screenshot">
    <%= image_tag url_for(@page.screenshot) if @page.screenshot.attachment %>
  </div>
  <div class="page-actions">
    <%= link_to 'Edit', edit_page_path(@page) %> |
    <%= link_to 'Back', pages_path %>
  </div>
</div>

app/views/welcome/index.html.erb
<p>You're on Rails!</p>